// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOxxnoLAonGUQrAdyJIHB4hAeOLLBLwB8',
    appId: '1:963860571570:web:e5de3fc281862bea0170ab',
    messagingSenderId: '963860571570',
    projectId: 'flutterfirebase-a0354',
    authDomain: 'flutterfirebase-a0354.firebaseapp.com',
    storageBucket: 'flutterfirebase-a0354.appspot.com',
    measurementId: 'G-6TR0NCJYYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5cGgyrmOloeEu_8VR1buWke5tN-l8ZWs',
    appId: '1:963860571570:android:5a19c1a55f375c260170ab',
    messagingSenderId: '963860571570',
    projectId: 'flutterfirebase-a0354',
    storageBucket: 'flutterfirebase-a0354.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXX9LDC5Wm8cHi-If8j8nBFTbBAQtdDiM',
    appId: '1:963860571570:ios:c1f7f23f851c75c20170ab',
    messagingSenderId: '963860571570',
    projectId: 'flutterfirebase-a0354',
    storageBucket: 'flutterfirebase-a0354.appspot.com',
    iosClientId: '963860571570-ts6ur2n8aer9tirs6rii5g06cvl0kt1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXX9LDC5Wm8cHi-If8j8nBFTbBAQtdDiM',
    appId: '1:963860571570:ios:c1f7f23f851c75c20170ab',
    messagingSenderId: '963860571570',
    projectId: 'flutterfirebase-a0354',
    storageBucket: 'flutterfirebase-a0354.appspot.com',
    iosClientId: '963860571570-ts6ur2n8aer9tirs6rii5g06cvl0kt1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
